var namespace_doloro_1_1_invetory_system =
[
    [ "DebugTools", "namespace_doloro_1_1_invetory_system_1_1_debug_tools.html", "namespace_doloro_1_1_invetory_system_1_1_debug_tools" ],
    [ "Demo", "namespace_doloro_1_1_invetory_system_1_1_demo.html", "namespace_doloro_1_1_invetory_system_1_1_demo" ],
    [ "Features", "namespace_doloro_1_1_invetory_system_1_1_features.html", "namespace_doloro_1_1_invetory_system_1_1_features" ],
    [ "Modules", "namespace_doloro_1_1_invetory_system_1_1_modules.html", "namespace_doloro_1_1_invetory_system_1_1_modules" ],
    [ "Tests", "namespace_doloro_1_1_invetory_system_1_1_tests.html", "namespace_doloro_1_1_invetory_system_1_1_tests" ],
    [ "UI", "namespace_doloro_1_1_invetory_system_1_1_u_i.html", "namespace_doloro_1_1_invetory_system_1_1_u_i" ],
    [ "AEntityFeature", "class_doloro_1_1_invetory_system_1_1_a_entity_feature.html", "class_doloro_1_1_invetory_system_1_1_a_entity_feature" ],
    [ "AFeaturesExtendingResource", "class_doloro_1_1_invetory_system_1_1_a_features_extending_resource.html", "class_doloro_1_1_invetory_system_1_1_a_features_extending_resource" ],
    [ "AItemFeature", "class_doloro_1_1_invetory_system_1_1_a_item_feature.html", "class_doloro_1_1_invetory_system_1_1_a_item_feature" ],
    [ "AMaskStorageFeature", "class_doloro_1_1_invetory_system_1_1_a_mask_storage_feature.html", "class_doloro_1_1_invetory_system_1_1_a_mask_storage_feature" ],
    [ "AStorageFeature", "class_doloro_1_1_invetory_system_1_1_a_storage_feature.html", "class_doloro_1_1_invetory_system_1_1_a_storage_feature" ],
    [ "Constants", "class_doloro_1_1_invetory_system_1_1_constants.html", "class_doloro_1_1_invetory_system_1_1_constants" ],
    [ "IReservationAgent", "interface_doloro_1_1_invetory_system_1_1_i_reservation_agent.html", "interface_doloro_1_1_invetory_system_1_1_i_reservation_agent" ],
    [ "Item", "class_doloro_1_1_invetory_system_1_1_item.html", "class_doloro_1_1_invetory_system_1_1_item" ],
    [ "ItemEditor", "class_doloro_1_1_invetory_system_1_1_item_editor.html", null ],
    [ "Storage", "class_doloro_1_1_invetory_system_1_1_storage.html", "class_doloro_1_1_invetory_system_1_1_storage" ],
    [ "StorageCaller", "class_doloro_1_1_invetory_system_1_1_storage_caller.html", "class_doloro_1_1_invetory_system_1_1_storage_caller" ],
    [ "StorageCallerEditor", "class_doloro_1_1_invetory_system_1_1_storage_caller_editor.html", null ],
    [ "StorageEditor", "class_doloro_1_1_invetory_system_1_1_storage_editor.html", "class_doloro_1_1_invetory_system_1_1_storage_editor" ],
    [ "StoragesDatabase", "class_doloro_1_1_invetory_system_1_1_storages_database.html", "class_doloro_1_1_invetory_system_1_1_storages_database" ],
    [ "StoragesService", "class_doloro_1_1_invetory_system_1_1_storages_service.html", "class_doloro_1_1_invetory_system_1_1_storages_service" ],
    [ "TransactionService", "class_doloro_1_1_invetory_system_1_1_transaction_service.html", "class_doloro_1_1_invetory_system_1_1_transaction_service" ]
];