var namespace_doloro_1_1_a_i_1_1_d_a_i_debugger_1_1_patching_tool_1_1_scripts_patching_tool =
[
    [ "ScriptsPatcher", "class_doloro_1_1_a_i_1_1_d_a_i_debugger_1_1_patching_tool_1_1_scripts_patching_tool_1_1_scripts_patcher.html", "class_doloro_1_1_a_i_1_1_d_a_i_debugger_1_1_patching_tool_1_1_scripts_patching_tool_1_1_scripts_patcher" ]
];